### ISSUE TITLE
A user should receive daily digest about today's activity

### ISSUE THREAD

**Issue by serhiir** [anatoliikryvishyn/TaDa#24]
Here is the mock-up:
![digest](https://cloud.githubusercontent.com/assets/2563629/8871308/0ebd02d0-31fd-11e5-80a6-c9b9eaecfb29.jpg)

Colors:
- Header and footer: `#1e8cd4`
- Completed amount: `#34ad00`
- Remaining amount: `#1f8cd3`

**Comment by anatoliikryvishyn** [comment]
A User should receive daily digest about today's activity such as completed todos, new lists and total statistic about completed and remaining todos.

**Comment by anatoliikryvishyn** [comment]
@serhiir, as for me we can divide this issue in such way, because it is too complex:
1. In this issue system will gather data about daily activity and manually ( by some link ) user could see the result ( it could be some other page, or maybe manually send mail )
2. Will automatic send data on mail in specific time every day.

But, in this way, first issue for me will be also complex, so maybe it will be good to divide it on 
3 parts: total statistic, completed todos, new lists?

**Comment by serhiir** [comment]
@anatoliikryvishyn, Sounds good. Please compose user stories - share their names here for now in order to conform them.

I suggest start from a total statistics. Completed todos and new lists let's postpone unless auto sending works.

**Comment by anatoliikryvishyn** [comment]
@serhiir , here are received user stories:
1. [A user should see total statistic about daily activity](https://github.com/anatoliikryvishyn/TaDa/issues/25)
2. [A user should receive daily digest about total statistic](https://github.com/anatoliikryvishyn/TaDa/issues/26)
3. [A user should receive daily digest about completed items](https://github.com/anatoliikryvishyn/TaDa/issues/27)
4. [A user should receive daily digest about new lists](https://github.com/anatoliikryvishyn/TaDa/issues/28)

**Comment by serhiir** [comment]
@anatoliikryvishyn OK

**Comment by serhiir** [comment]
Closing as it was split into the user stories.
